// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjfiwpjtuondagjfrdim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqZml3cGp0dW9uZGFnamZyZGltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MTU4NTgsImV4cCI6MjA1NTE5MTg1OH0.oFiQqxfdB61GjCy2SN0Qa6qSkF8Ct4TXilpPvcXvp1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);